[package]
name = "color-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = { version = "0.6" }
tokio = { version = "1.36", features = [ "full" ] }
dotenv = "0.15"
rusqlite = "0.31"
hex_color = "3"
